### ISSUE TITLE
tar_load() not loading all targets

### ISSUE THREAD

**Issue by jameelalsalam** [ropensci/targets#314] opened 2021-02-16 21:30 UTC
## Prework

* [X] Read and agree to the [code of conduct](https://ropensci.org/code-of-conduct/) and [contributing guidelines](https://github.com/ropensci/targets/blob/main/CONTRIBUTING.md).
* [X] Confirm that your issue is most likely a genuine bug in the `targets` package itself and not a user error or known limitation. For usage issues and troubleshooting, please post to the [discussions](https://github.com/ropensci/targets/discussions) instead.
* [X] If there is [already a relevant issue](https://github.com/ropensci/targets/issues), whether open or closed, comment on the existing thread instead of posting a new issue.
* [X] Post a [minimal reproducible example](https://www.tidyverse.org/help/) like [this one](https://github.com/ropensci/targets/issues/256#issuecomment-754229683) so the maintainer can troubleshoot the problems you identify. A reproducible example is:
    * [ ] **Runnable**: post enough R code and data so any onlooker can create the error on their own computer.
    * [ ] **Minimal**: reduce runtime wherever possible and remove complicated details that are irrelevant to the issue at hand.
    * [ ] **Readable**: format your code according to the [tidyverse style guide](https://style.tidyverse.org/).

## Description

Based on the [documentation](https://docs.ropensci.org/targets/reference/tar_load.html) for the names parameter to tar_load, I would expect tar_load() with unspecified names to load all targets, but it says 'Found no targets to load'. I apologize if I am misinterpreting the docs, I am trying to learn targets right now.

Excerpt:
names | Names of the targets to build or check. Set to NULL to check/build all the targets (default). Otherwise, you can supply symbols, a character vector, or tidyselect helpers like starts_with().

## Reproducible example

``` r
library("targets")

tar_dir({ # tar_dir() runs code from a temporary directory.
  tar_script({
    list(
      tar_target(y1, 1 + 1),
      tar_target(y2, 1 + 1),
      tar_target(z, y1 + y2)
    )
  }, ask = FALSE)
  tar_make()
  tar_load()
})
#> * run target y1
#> * run target y2
#> * run target z
#> * end pipeline
#> x Found no targets to load.
```

<sup>Created on 2021-02-16 by the [reprex package](https://reprex.tidyverse.org) (v1.0.0)</sup>

<details style="margin-bottom:10px;">
<summary>
Session info
</summary>

``` r
sessionInfo()
#> R version 3.6.3 (2020-02-29)
#> Platform: x86_64-w64-mingw32/x64 (64-bit)
#> Running under: Windows 10 x64 (build 17763)
#> 
#> Matrix products: default
#> 
#> locale:
#> [1] LC_COLLATE=English_United States.1252 
#> [2] LC_CTYPE=English_United States.1252   
#> [3] LC_MONETARY=English_United States.1252
#> [4] LC_NUMERIC=C                          
#> [5] LC_TIME=English_United States.1252    
#> 
#> attached base packages:
#> [1] stats     graphics  grDevices datasets  utils     methods   base     
#> 
#> other attached packages:
#> [1] targets_0.1.0.9000
#> 
#> loaded via a namespace (and not attached):
#>  [1] igraph_1.2.6      rstudioapi_0.13   knitr_1.31        magrittr_2.0.1   
#>  [5] tidyselect_1.1.0  R6_2.5.0          rlang_0.4.10      stringr_1.4.0    
#>  [9] highr_0.8         tools_3.6.3       data.table_1.13.6 xfun_0.21        
#> [13] cli_2.3.0         withr_2.4.1       ellipsis_0.3.1    htmltools_0.5.1.1
#> [17] yaml_2.2.1        assertthat_0.2.1  digest_0.6.27     lifecycle_1.0.0  
#> [21] tibble_3.0.6      crayon_1.4.1      processx_3.4.5    purrr_0.3.4      
#> [25] callr_3.5.1       vctrs_0.3.6       fs_1.5.0          ps_1.5.0         
#> [29] codetools_0.2-18  glue_1.4.2        evaluate_0.14     rmarkdown_2.6    
#> [33] reprex_1.0.0      stringi_1.5.3     pillar_1.4.7      compiler_3.6.3   
#> [37] renv_0.12.5       pkgconfig_2.0.3
```

</details>

## Expected result

I was expecting targets y1, y2, and z to be loaded.

**Comment by wlandau** [comment] 2021-02-16 23:20
Thanks. The behavior is as intended, but the docs and message are misleading. Now fixed.

**Closed by wlandau** 2021-02-16 23:20 UTC
Labels: topic: documentation

**Comment by malcolmbarrett** [comment] 2021-03-05 21:24
@wlandau is there a recommended way to load all targets if the default of `tar_load()` is not meant to do so?

**Comment by wlandau** [comment] 2021-03-05 21:29
`tar_load(everything())` does this. `tidyselect` is awesome, and `targets` embraces it for many of its exported functions.

**Comment by malcolmbarrett** [comment] 2021-03-05 21:29
Beautiful, thanks, Will!
